begin_integration_rk_variable_step_class – rklib
begin_integration_rk_variable_step_class Subroutine
10 statements
Source File
private subroutine begin_integration_rk_variable_step_class(me)
Begin a rk_variable_step_class integration.
Type Bound
rk_variable_step_class
Arguments
Type Intent Optional Attributes Name
class(rk_variable_step_class), intent(inout) :: me
Calls
Called by
Source Code
    subroutine begin_integration_rk_variable_step_class(me)
    class(rk_variable_step_class),intent(inout) :: me
    call me%begin() ! base
    ! variable step params:
    me%num_rejected_steps = 0
    me%last_accepted_step_size = zero
    select type (me)
    class is (rk_variable_step_fsal_class)
        call me%destroy_fsal_cache()
    end select
    end subroutine begin_integration_rk_variable_step_class
Call graph
begin_integration_rk_variable_step_class calls begin, destroy_fsal_cache
integrate_to_event_variable_step calls begin_integration_rk_variable_step_class
integrate_variable_step calls begin_integration_rk_variable_step_class
rklib_example calls integrate_variable_step