check_fsal_cache – rklib
check_fsal_cache Subroutine
18 statements
Source File
private subroutine check_fsal_cache(me, t, x, f)
Check the FSAL cache.
Type Bound
rk_variable_step_fsal_class
Arguments
Type Intent Optional Attributes Name
class(rk_variable_step_fsal_class), intent(inout) :: me
real(kind=wp), intent(in) :: t
real(kind=wp), intent(in), dimension(:) :: x
real(kind=wp), intent(out), dimension(:) :: f
Called by
Contents
Source Code
check_fsal_cache
Source Code
    subroutine check_fsal_cache(me,t,x,f)
        class(rk_variable_step_fsal_class),intent(inout) :: me
        real(wp),intent(in) :: t
        real(wp),dimension(:),intent(in)  :: x
        real(wp),dimension(:),intent(out) :: f
        logical :: fsal !! if we can avoid a step due to first-same-as-last
        fsal = .false.
        if (allocated(me%x_saved)) then
            if (size(x) == size(me%x_saved)) then
                fsal = all(x==me%x_saved) .and. t==me%t_saved
            end if
        end if
        if (fsal) then
            f = me%f_saved
        else
            call me%f(t, x, f)
        end if
    end subroutine check_fsal_cache
Call graph
rkbs32 calls check_fsal_cache, rkbs32
rkdp54 calls check_fsal_cache, rkdp54
rkpp54 calls check_fsal_cache, rkpp54
rkpp54b calls check_fsal_cache, rkpp54b
rks54 calls check_fsal_cache, rks54
rkt54 calls check_fsal_cache, rkt54
rktf65 calls check_fsal_cache, rktf65
rkv65e calls check_fsal_cache, rkv65e
rkv65r calls check_fsal_cache, rkv65r