destroy_fsal_cache – rklib
destroy_fsal_cache Subroutine
6 statements
Source File
private subroutine destroy_fsal_cache(me)
Destructor for the FSAL variables.
Type Bound
rk_variable_step_fsal_class
Arguments
Type Intent Optional Attributes Name
class(rk_variable_step_fsal_class), intent(inout) :: me
Called by
Source Code
    subroutine destroy_fsal_cache(me)
        class(rk_variable_step_fsal_class),intent(inout) :: me
        if (allocated(me%t_saved)) deallocate(me%t_saved)
        if (allocated(me%x_saved)) deallocate(me%x_saved)
        if (allocated(me%f_saved)) deallocate(me%f_saved)
    end subroutine destroy_fsal_cache
Call graph
begin_integration_rk_variable_step_class calls destroy_fsal_cache
integrate_to_event_variable_step calls begin_integration_rk_variable_step_class
integrate_variable_step calls begin_integration_rk_variable_step_class
rklib_example calls integrate_variable_step