order – rklib
order Function
7 statements
Source File
private pure function order(me) result(p)
Returns the order of the RK method
Type Bound
rk_variable_step_class
Arguments
Type Intent Optional Attributes Name
class(rk_variable_step_class), intent(in) :: me
Return Value integer
order of the method
Calls
Called by
Source Code
    pure function order(me) result(p)
        class(rk_variable_step_class),intent(in) :: me
        integer :: p !! order of the method
        type(rklib_properties) :: properties
        properties = me%properties()
        p = properties%order
    end function order
Call graph
order calls properties
hinit calls order
hstart calls order
integrate_to_event_variable_step calls order, compute_initial_step
integrate_variable_step calls order, compute_initial_step
compute_initial_step calls hinit, hstart
rklib_example calls integrate_variable_step