raise_exception – rklib
raise_exception Subroutine
8 statements
Source File
private subroutine raise_exception(me, error_code)
Raise an exception.
Type Bound
rk_class
Arguments
Type Intent Optional Attributes Name
class(rk_class), intent(inout) :: me
integer, intent(in) :: error_code
the error to raise
Called by
Source Code
    subroutine raise_exception(me, error_code)
        class(rk_class),intent(inout) :: me
        integer,intent(in) :: error_code !! the error to raise
        me%istatus = error_code
        if (error_code<0 .and. me%stop_on_errors) then
            error stop trim(rklib_error_messages(error_code))
        end if
    end subroutine raise_exception
Call graph
initialize_variable_step calls raise_exception
integrate_fixed_step calls raise_exception
integrate_to_event_fixed_step calls raise_exception
integrate_to_event_variable_step calls raise_exception
integrate_variable_step calls raise_exception
rklib_example calls initialize_variable_step, integrate_variable_step