rkbs32 – rklib
rkbs32 Module Procedure
25 statements
Source File
module procedure rkbs32 module subroutine rkbs32(me, t, x, h, xf, xerr) Interface →
Bogacki-Shampine 3(2) method
Reference
Bogacki, P and Shampine, L. F. (1989), "A 3(2) pair of Runge-Kutta formulas", Applied Mathematics Letters, 2 (4): 321-325
Note
This is a first-same-as-last (FSAL) step.
Arguments
Type Intent Optional Attributes Name
class(rkbs32_class), intent(inout) :: me
real(kind=wp), intent(in) :: t
initial time
real(kind=wp), intent(in), dimension(me%n) :: x
initial state
real(kind=wp), intent(in) :: h
time step
real(kind=wp), intent(out), dimension(me%n) :: xf
state at time t+h
real(kind=wp), intent(out), dimension(me%n) :: xerr
truncation error estimate for x
Calls
Call graph
rkbs32 calls f, funcs, check_fsal_cache, set_fsal_cache
check_fsal_cache calls f
set_fsal_cache calls f