rkdp54 – rklib
rkdp54 Module Procedure
54 statements
Source File
module procedure rkdp54 module subroutine rkdp54(me, t, x, h, xf, xerr) Interface →
Dormand-Prince 5(4) method (RKDP or DOPRI)
Reference
Dormand, J. R.; Prince, P. J. (1980), "A family of embedded Runge-Kutta formulae", Journal of Computational and Applied Mathematics, 6 (1): 19-26
https://en.wikipedia.org/wiki/Dormand-Prince_method
Note
This is a first-same-as-last (FSAL) step.
Arguments
Type Intent Optional Attributes Name
class(rkdp54_class), intent(inout) :: me
real(kind=wp), intent(in) :: t
initial time
real(kind=wp), intent(in), dimension(me%n) :: x
initial state
real(kind=wp), intent(in) :: h
time step
real(kind=wp), intent(out), dimension(me%n) :: xf
state at time t+h
real(kind=wp), intent(out), dimension(me%n) :: xerr
truncation error estimate for x
Calls
Call graph
rkdp54 calls f, funcs, check_fsal_cache, set_fsal_cache
check_fsal_cache calls f
set_fsal_cache calls f