rkt54 – rklib
rkt54 Module Procedure
53 statements
Source File
module procedure rkt54 module subroutine rkt54(me, t, x, h, xf, xerr) Interface →
Tsitouras 5(4) method
Reference
Ch. Tsitouras, "Runge-Kutta pairs of order 5(4) satisfying only the first column simplifying assumption", Computers & Mathematics with Applications, Vol. 62, No. 2, pp. 770 - 775, 2011.
Higher-precision coefficients
Arguments
Type Intent Optional Attributes Name
class(rkt54_class), intent(inout) :: me
real(kind=wp), intent(in) :: t
initial time
real(kind=wp), intent(in), dimension(me%n) :: x
initial state
real(kind=wp), intent(in) :: h
time step
real(kind=wp), intent(out), dimension(me%n) :: xf
state at time t+h
real(kind=wp), intent(out), dimension(me%n) :: xerr
truncation error estimate for x
Calls
Call graph
rkt54 calls f, funcs, check_fsal_cache, set_fsal_cache
check_fsal_cache calls f
set_fsal_cache calls f