rkv65e – rklib
rkv65e Module Procedure
63 statements
Source File
module procedure rkv65e module subroutine rkv65e(me, t, x, h, xf, xerr) Interface →
Verner's "most efficient" Runge-Kutta (9,6(5)) pair.
Reference
J.H. Verner, "Strategies for deriving new explicit Runge-Kutta pairs", Annals of Num. Math 1 1994, 225-244.
Jim Verner's Refuge for Runge-Kutta Pairs
Rational coefficients
Floating point coefficients
Note
This is a first-same-as-last (FSAL) step.
Arguments
Type Intent Optional Attributes Name
class(rkv65e_class), intent(inout) :: me
real(kind=wp), intent(in) :: t
initial time
real(kind=wp), intent(in), dimension(me%n) :: x
initial state
real(kind=wp), intent(in) :: h
time step
real(kind=wp), intent(out), dimension(me%n) :: xf
state at time t+h
real(kind=wp), intent(out), dimension(me%n) :: xerr
truncation error estimate for x
Calls
Call graph
rkv65e calls f, funcs, check_fsal_cache, set_fsal_cache
check_fsal_cache calls f
set_fsal_cache calls f