rkv65r – rklib
rkv65r Module Procedure
62 statements
Source File
module procedure rkv65r module subroutine rkv65r(me, t, x, h, xf, xerr) Interface →
Verner's "most robust" Runge-Kutta (9,6(5)) pair.
Reference
J.H. Verner, "Strategies for deriving new explicit Runge-Kutta pairs", Annals of Num. Math 1 1994, 225-244.
Jim Verner's Refuge for Runge-Kutta Pairs
Rational coefficients
Floating point coefficients
Note
This is a first-same-as-last (FSAL) step.
Arguments
Type Intent Optional Attributes Name
class(rkv65r_class), intent(inout) :: me
real(kind=wp), intent(in) :: t
initial time
real(kind=wp), intent(in), dimension(me%n) :: x
initial state
real(kind=wp), intent(in) :: h
time step
real(kind=wp), intent(out), dimension(me%n) :: xf
state at time t+h
real(kind=wp), intent(out), dimension(me%n) :: xerr
truncation error estimate for x
Calls
Call graph
rkv65r calls f, funcs, check_fsal_cache, set_fsal_cache
check_fsal_cache calls f
set_fsal_cache calls f