set_fsal_cache – rklib
set_fsal_cache Subroutine
10 statements
Source File
private subroutine set_fsal_cache(me, t, x, f)
Compute the function and add it to the FSAL cache.
Type Bound
rk_variable_step_fsal_class
Arguments
Type Intent Optional Attributes Name
class(rk_variable_step_fsal_class), intent(inout) :: me
real(kind=wp), intent(in) :: t
real(kind=wp), intent(in), dimension(:) :: x
real(kind=wp), intent(out), dimension(:) :: f
Called by
Contents
Source Code
set_fsal_cache
Source Code
    subroutine set_fsal_cache(me,t,x,f)
        class(rk_variable_step_fsal_class),intent(inout) :: me
        real(wp),intent(in) :: t
        real(wp),dimension(:),intent(in)  :: x
        real(wp),dimension(:),intent(out) :: f
        call me%f(t,x,f)
        me%t_saved = t
        me%x_saved = x
        me%f_saved = f
    end subroutine set_fsal_cache
Call graph
rkbs32 calls set_fsal_cache, rkbs32
rkdp54 calls set_fsal_cache, rkdp54
rkpp54 calls set_fsal_cache, rkpp54
rkpp54b calls set_fsal_cache, rkpp54b
rks54 calls set_fsal_cache, rks54
rkt54 calls set_fsal_cache, rkt54
rktf65 calls set_fsal_cache, rktf65
rkv65e calls set_fsal_cache, rkv65e
rkv65r calls set_fsal_cache, rkv65r