rklib_example – rklib
rklib_example Program
28 statements
Source File
Uses
rklib_module
iso_fortran_env
Calls
Variables
Type Attributes Name Initial
integer, parameter :: n = 2
dimension of the system
real(kind=wp), parameter :: tol = 1.0e-12_wp
integration tolerance
real(kind=wp), parameter :: t0 = 0.0_wp
initial t value
real(kind=wp), parameter :: dt = 1.0_wp
initial step size
real(kind=wp), parameter :: tf = 100.0_wp
endpoint of integration
real(kind=wp), parameter, dimension(n) :: x0 = [0.0_wp, 0.1_wp]
initial x value
real(kind=wp), dimension(n) :: xf
final x value
type(rktp86_class) :: prop
character(len=:), allocatable :: message
Subroutines
subroutine fvpol(me, t, x, f)
Right-hand side of van der Pol equation
Arguments
Type Intent Optional Attributes Name
class(rk_class), intent(inout) :: me
real(kind=wp), intent(in) :: t
real(kind=wp), intent(in), dimension(:) :: x
real(kind=wp), intent(out), dimension(:) :: f
Source Code
program rklib_example
  use rklib_module, wp => rk_module_rk
  use iso_fortran_env, only: output_unit
  implicit none
  integer,parameter :: n = 2 !! dimension of the system
  real(wp),parameter :: tol = 1.0e-12_wp !! integration tolerance
  real(wp),parameter :: t0 = 0.0_wp !! initial t value
  real(wp),parameter :: dt = 1.0_wp !! initial step size
  real(wp),parameter :: tf = 100.0_wp !! endpoint of integration
  real(wp),dimension(n),parameter :: x0 = [0.0_wp,0.1_wp] !! initial x value
  real(wp),dimension(n) :: xf !! final x value
  type(rktp86_class) :: prop
  character(len=:),allocatable :: message
  call prop%initialize(n=n,f=fvpol,rtol=[tol],atol=[tol])
  call prop%integrate(t0,x0,dt,tf,xf)
  call prop%status(message=message)
  write (output_unit,'(A)') message
  write (output_unit,'(A,F7.2/,A,2E18.10)') &
              'tf =',tf ,'xf =',xf(1),xf(2)
contains
  subroutine fvpol(me,t,x,f)
    !! Right-hand side of van der Pol equation
    class(rk_class),intent(inout)     :: me
    real(wp),intent(in)               :: t
    real(wp),dimension(:),intent(in)  :: x
    real(wp),dimension(:),intent(out) :: f
    f(1) = x(2)
    f(2) = 0.2_wp*(1.0_wp-x(1)**2)*x(2) - x(1)
  end subroutine fvpol
end program rklib_example
Call graph
rklib_example calls initialize_variable_step, integrate_variable_step, rk_class_status
initialize_variable_step calls init, raise_exception
integrate_variable_step calls begin_integration_rk_variable_step_class, compute_initial_step, compute_stepsize, export_point, order, raise_exception, step
begin_integration_rk_variable_step_class calls begin, destroy_fsal_cache
compute_initial_step calls f, hinit, hstart
order calls properties
hinit calls order, f
hstart calls order, f